{% set name = "imgviz" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2eb3968d6e2875cb0f8ad62a7fc2d6bed8c81671609a047f49ee74b3b7eb34e5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pillow >=5.3.0
    - pyyaml
    # contained in [all]
    - pyglet
    - scikit-image
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - imgviz

about:
  home: https://github.com/wkentaro/imgviz
  # Upstream asked for clarification:
  # https://github.com/wkentaro/imgviz/issues/11
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image Visualization Tools

extra:
  recipe-maintainers:
    - hmaarrfk
    - wkentaro
