{% set name = "imgviz" %}
{% set version = "1.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dad88868aa450deb105e08c389d3cc7ffd4f62cc7bc30885e33ce38ba2919a89

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pillow >=5.3.0
    - pyyaml
    # contained in [all]
    - pyglet
    - scikit-image
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - imgviz

about:
  home: https://github.com/wkentaro/imgviz
  # Upstream asked for clarification:
  # https://github.com/wkentaro/imgviz/issues/11
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image Visualization Tools

extra:
  recipe-maintainers:
    - hmaarrfk
    - wkentaro
