{% set name = "imgviz" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e81f4941ef1e9e6a11c1b317415da72a8fd66ff86b9c4941555dae270c4918e7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - numpy
    - pillow >=5.3.0
    # contained in [all]
    - pyglet
    - scikit-image
    - scikit-learn
    - libwebp

test:
  imports:
    - imgviz

about:
  home: https://github.com/wkentaro/imgviz
  # Upstream asked for clarification:
  # https://github.com/wkentaro/imgviz/issues/11
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Image Visualization Tools'

extra:
  recipe-maintainers:
    - hmaarrfk
    - wkentaro
