{% set version = "2.1.0" %}

package:
  name: imgviz
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/imgviz/imgviz-{{ version }}.tar.gz
  sha256: bc5cc8e1b98706b5a3baf773444e5fa16db47d47150e0752f3e4f1e8a3fc92e1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - python >={{ python_min }}
    - cmap >=0.1.0
    - matplotlib-base
    - numpy
    - pillow >=5.3.0
    - pyyaml
    # contained in [all]
    - pyglet
    - scikit-image
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - imgviz

about:
  home: https://github.com/wkentaro/imgviz
  # Upstream asked for clarification:
  # https://github.com/wkentaro/imgviz/issues/11
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Image Visualization Tools

extra:
  recipe-maintainers:
    - hmaarrfk
    - wkentaro
