{% set name = "imgviz" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b93643972e92a3284245f5d8441a0a5a7a384cdea336f7a8d12d29399410c718

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - numpy
    - pillow >=5.3.0
    # contained in [all]
    - scikit-image
    - scikit-learn

test:
  imports:
    - imgviz

about:
  home: https://github.com/wkentaro/imgviz
  # Upstream asked for clarification:
  # https://github.com/wkentaro/imgviz/issues/11
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Image Visualization Tools'

extra:
  recipe-maintainers:
    - hmaarrfk
    - wkentaro
